server:
  port: 8001
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-instances
          uri: https://github.com/caitoVilas/microservices-exercises
          search-paths: config-data
  application:
    name: config-server
